Add support for dependency groups
python-poetry/poetry-plugin-bundle pull request #26
Opened 2022-08-31 18:49 UTC by tofay

By making `BundleCommand` inherit from poetry's `GroupCommand`, and passing the detected groups through to the venv bundler.

Fixes https://github.com/python-poetry/poetry-plugin-bundle/issues/8

2022-09-16 10:46 UTC, SamambaMan commented
Hey! 

I need this SO BADLY and would be awesome if the PR were accepted.
Any chances? :D

Thanks for the great work

2022-11-01 10:36 UTC, connelldave commented
Hello - ➕ this solves a blocking problem for my project. Curious if this is a change you're open to accepting? Thanks!

2022-11-02 11:16 UTC, mxab commented
This looks really helpful!
@neersighted would it be possible to ping the reviewers, would be a shame if that PR goes to waste :)

2022-11-02 15:51 UTC, radoering requested changes
Sorry for the late feedback. Overall this looks good to me. Can you add some simple tests with the different options in `tests/console/commands/bundle/test_venv.py`, please?

2022-11-02 15:51 UTC, radoering commented on tests/bundlers/test_venv_bundler.py
> +    from poetry.puzzle.exceptions import SolverProblemError
This import should be global.

2022-11-03 21:18 UTC, tofay commented
I've added the tests as suggested.

2022-11-04 13:33 UTC, radoering approved these changes

2022-11-04 13:33 UTC, merged